### PR TITLE
Verify credentials

### PR DESCRIPTION
**Pull request by einarmo**
Verify that OIDC read/write credentials are valid before creating transformations.

This just calls token/inspect with the credentials, then throws errors based on what is wrong with them, if anything.

This requires groups:list and projects:list.

### CODE REVIEW

**Comment by einarmo** [comment]
Test fails in a fairly expected way: the deployed transformations from oidc_examples/ do not have valid credentials. How should we fix this?

**Comment by einarmo** [comment]
> Seems to me this is the error?
> 
> > Transformation root folder not found: invalid_path

That's the parameter for the test, which is parameterized. I think the actual failure is this: `AssertionError: assert 'Number of' in 'Deploying transformation...\nCredentials for test-cli-transform-oidc write failed to validate: Error generating access token: insecure_transport, 400, OAuth 2 MUST utilize https.\n'` so we expect the result to be `Number of transformations deployed...` or something along those lines, and get the credentials failure instead.

**Comment by emelvarol-cognite** [comment]
strange, I updated the secret and it should be a valid one. :/

**Comment by einarmo** [comment]
> strange, I updated the secret and it should be a valid one. :/

The error is from some URL I think, the token URL is invalid maybe?

**Comment by emelvarol-cognite** [comment]
> > strange, I updated the secret and it should be a valid one. :/
> 
> The error is from some URL I think, the token URL is invalid maybe?

I actually tried it last night, deployed a transformation and ran it. It worked for that case 🤔 🤯  I'll update and check again

**Comment by einarmo** [comment]
I guess it could be my code

> > > strange, I updated the secret and it should be a valid one. :/
> > 
> > 
> > The error is from some URL I think, the token URL is invalid maybe?
> 
> I actually tried it last night, deployed a transformation and ran it. It worked for that case 🤔 🤯 I'll update and check again

I don't see any credentials being injected to the environment variables used in the oidc_examples folders.

**Comment by emelvarol-cognite** [comment]
> I guess it could be my code
> 
> > > > strange, I updated the secret and it should be a valid one. :/
> > > 
> > > 
> > > The error is from some URL I think, the token URL is invalid maybe?
> > 
> > 
> > I actually tried it last night, deployed a transformation and ran it. It worked for that case 🤔 🤯 I'll update and check again
> 
> I don't see any credentials being injected to the environment variables used in the oidc_examples folders.

They should be injected because I could run the deployed transformations just now, why do you think they are not injected?

**Comment by emelvarol-cognite** [comment]
> I guess it could be my code
> 
> > > > strange, I updated the secret and it should be a valid one. :/
> > > 
> > > 
> > > The error is from some URL I think, the token URL is invalid maybe?
> > 
> > 
> > I actually tried it last night, deployed a transformation and ran it. It worked for that case 🤔 🤯 I'll update and check again
> 
> I don't see any credentials being injected to the environment variables used in the oidc_examples folders.

Ok I know the problem, oidc_examples was designed to be used in deploy action step. I used it in the integration test and didn't provide all the env vars to test step and it didn't argue before because we didn't validate it. I'll fix it in a sec.

**Comment by emelvarol-cognite** [comment]
I solved the issue hardcoding some environment variables used in manifests. It works for deploy action but I couldn't manage to pass env vars into pytest except for secrets. It fails with "Skipping virtualenv creation, as specified in config file. github". It works but i don't like my solution to this issue

**Review by emelvarol-cognite — APPROVED** [review]
Nice

**Pull request merged**
