### PR TITLE
Support string for destination property

### PR DESCRIPTION
**Pull request by emelvarol-cognite**
The old CLI expects string on destination if the target is not raw, let's support that style as well.

### CODE REVIEW

**Comment by hakontro** [comment]
Wouldn't it be better to fix the migration here? Save people some time by letting them know early that there's a problem.

**Comment by emelvarol-cognite** [comment]
> Wouldn't it be better to fix the migration here? Save people some time by letting them know early that there's a problem.

I thought both styles are acceptable, don't you think?

**Comment by hakontro** [comment]
So this is to let people use `destination: "assets` when they're not using RAW, right? Is it at least possible to still use the enum here, so the manifest fails if the string is wrong?

**Review by hakontro — APPROVED** [review]

**Comment by emelvarol-cognite** [comment]
> So this is to let people use `destination: "assets` when they're not using RAW, right? Is it at least possible to still use the enum here, so the manifest fails if the string is wrong?

this makes total sense, will change it!

**Pull request merged**
